### ISSUE TITLE
"Value cannot be null" exception raised when dealing with nested null values

### ISSUE THREAD

**Issue by apetrut** [danielwertheim/structurizer#7]
Hi, 

After I integrated Structurizer nuget Version=4.0.0.14 into a desktop app, I tried to generate indexes for two similar objects with just a couple of different properties between them. 
The second object had several null properties on the 3rd and 4th level down the hierarchy and because of this the error below occured:

![get_builder_error](https://user-images.githubusercontent.com/13006228/71187150-2bdc2b00-2287-11ea-9c61-d994c15b19b2.png)

Going through the stack trace I found out that the error was being raised at this stage:

![index_accessor_error](https://user-images.githubusercontent.com/13006228/71191055-5da4c000-228e-11ea-9395-7e70fa032a07.png)

If I have both objects with all the properties filled I don't get any error.

Thanks.

**Comment by apetrut** [comment]
I could also reproduce the problem with the Sample project provided in the Structurizer solution.
I have created a nested level for the OrderLine object and I could re-create the problem (i.e.: TestProp with null children).

`new OrderLine
                    {
                        TestProp = new Prop()
                        {
                            Name = null,
                            Value = null,
                        },
                        ArticleNo = null,
                        Qty = 42,
                        Props =  new List<Prop>
                        {
                            new Prop
                            {
                                Name = "Key-Line0-Item0",
                                Value = "Value-Line0-Item0",
                            },
                            new Prop
                            {
                                Name = "Key-Line0-Item1",
                                Value = "Value-Line0-Item1"
                            }
                        }
                    }`

I suggest to add the null check in order to fix this issue.
Should I submit a pull request for this?

Thanks,
A

**Comment by danielwertheim** [comment]
Hi, thanks for the detailed info. I would happily accept a PR.

**Comment by apetrut** [comment]
Hi Daniel,

I have created a PR. When you have time can you take a look at it?

Thanks,
A

**Comment by danielwertheim** [comment]
Closed via #8

**Comment by danielwertheim** [comment]
@apetrut Thanks for the contrib. A release should now be out.
